### PR TITLE
Fixes bugs from other software updates.

### PR DESCRIPTION
**Pull request by mathuin**
Docker changed how it interprets commands in docker-compose.yml files. Several
containers previously had the command "true" which is now being parsed as a
boolean.  The commands have been replaced with "/bin/true".

The integration test script had a Docker test which depended upon cgroups.
This feature is no longer required to run Docker, so the test sometimes fails.
The new test checks for a file within the container which is guaranteed to be
present in a container but should never be present outside a container.

Finally, recent versions of BioPython now return more than six values from the
DSSP structure.  This code only uses six values, so the tuple must be sliced.

### CODE REVIEW

**Comment by Sentient07** [comment]
Hello @mathuin . So glad to have woken up to this notification. Hope you're doing well :smile: . Would be happy to continue my contributions :)

**Comment by pop** [comment]
lgtm +1

**Comment by mathuin** [comment]
@Sentient07 Long time no chat!  I would love to chat with you sometime over the next few weeks about your outstanding PRs and get them merged before summer starts.  Pop into the IRC channel sometime and say hi! :-)

**Comment by Sentient07** [comment]
Hello @mathuin . Sorry for the delayed reply. Things have been a little hectic. I had few project submissions the week before and mid term exams till next wednesday. I am free after Thursday. When would it be apt for you ? :-)

**Comment by mathuin** [comment]
@Sentient07 how about next Monday, around 0900 PDT?  I should be back in the office by then. :-)

**Comment by Sentient07** [comment]
@mathuin Sure! I am looking forward :smile:

**Comment by mathuin** [comment]
Okay, having had no negative reports and finding these changes to be necessary for me to continue work on a blocking issue, I'm going to commit these to develop.

**Pull request merged**
