### PR TITLE
saving image in png format fixed

### PR DESCRIPTION
**Pull request by Sentient07**

### CODE REVIEW

**Comment by mathuin** [comment]
I have personally confirmed that this code works as described.

The changelog needs updating, as does the issue at code.osuosl.org.

Once those are done, I'll merge with develop.  Good job! :sparkles:

**Comment by Sentient07** [comment]
:+1:  :)

**Comment by Sentient07** [comment]
@mathuin this could be merged ? 
My finals have begun and I'm not finding time to drop by IRC. I'll be free from 14th May. As usual, my holidays begin then. Would be happy to catch up on IRC :)

**Comment by mathuin** [comment]
We should merge your code soon.  We have a somewhat urgent patch which needs to be committed first, but this should come next.  Thanks for reminding me!  I look forward to seeing you on IRC after your finals -- hopefully we can merge the code then! :-)

**Comment by mathuin** [comment]
This code has been merged with changes.  Yay!

**Pull request closed without merging**
