### PR TITLE
Occupancy Test

### PR DESCRIPTION
**Pull request by Sentient07**
Initial commit to PR. I'm unable to add to the database using the instructions given in l:30, pgd_splicer/tests.py. 
What I've done : 
Ran that first command in the l:30, pgd_splicer/tests.py. 
The second command in the instructions, 
then the first one, again. Then,
I tried to view the data in the database by $docker-compose run web python manage.py dbshell command, but apparently the tables were NULL. I'm confused as where I have gone wrong and need your ( @mathuin ) help here, as usual.
please go through and reply at your convenience :)

### CODE REVIEW

**Comment by Sentient07** [comment]
A little more insight, I executed the script to populate the DB like :
$ docker-compose run web python pgd_splicer/ProcessPDBTask.py --pipein < ./pgd_splicer/testfiles/fixture_selection.txt
I changed the setting.py file in accordance with l:24 and l:25 in pgd_splicer/tests.py , still couldn't see anything the tables.
I also checked from the CLI of the MySQL container, I found the tables empty there as well. MySQL container's logs : http://pastebin.com/2MB8FAQm .
I really have a gut feel that it was really easy and I just blew up the situation :(

**Comment by mathuin** [comment]
Okay, the commands are working for me.
1. Build and run a new web container.
   
   ```
   $ docker-compose build web && docker-compose run web
   ```
2. Once inside this container, confirm the database is empty:
   
   ```
   [root@04b3a5ad0e01 pgd]# python manage.py shell
   Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
   [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
   Type "help", "copyright", "credits" or "license" for more information.
   (InteractiveConsole)
   >>> from pgd_core.models import Protein
   >>> Protein.objects.count()
   0
   >>
   ```
3.  Run the first command listed in the tests.py file.
   
   ```
   [root@04b3a5ad0e01 pgd]#  ./pgd_splicer/ProcessPDBTask.py --pipein < ./pgd_splicer/testfiles/fixture_selection.txt
   ```
4.  A lot of stuff passes by.  Rerun the test in step 2.  Should show six proteins.
5.  Run the second command listed in the tests.py file.
   
   ```
   [root@04b3a5ad0e01 pgd]# python manage.py dumpdata pgd_core --indent 2 --format json > whatever.json
   ```
6.  Look online for how to copy files from containers to hosts:  http://stackoverflow.com/questions/22049212/docker-copy-file-from-container-to-host tells you how!  Run that command from a local shell:
   
   ```
   $ docker cp $(docker ps -l -q):/opt/pgd/whatever.json .
   $ ls -al whatever.json 
   -rw-r--r-- 1 jmt jmt 7319090 Jun  7 14:20 whatever.json
   ```

Now that you have the JSON file you can copy it over the existing one in the repository and commit it, or just test with it, or whatever you like. :-)

**Comment by Sentient07** [comment]
Yeah, those were the exact same steps that I followed. But after step 3 , when I try to count the number of proteins, I still get 0.  That's what surprises me..

**Comment by mathuin** [comment]
Try to remove all your containers then start over:

```
$ docker-compose rm -f
```

**Comment by Sentient07** [comment]
@mathuin , is it fine now ? I couldn't find any difference between upstream/develop and remote/OccTest apart from what i've committed. Please let me know if I need to change more :)

**Pull request closed without merging**
