### PR TITLE
Error in saving image in PNG format fixed

### PR DESCRIPTION
**Pull request by Sentient07**

### CODE REVIEW

**Comment by Sentient07** [comment]
Not sure where I should have that test, so added a separate file for that test. I'm aware of the tests.py and the PersistingSearchOptions class in that file. I'm not sure whether this test will fit in there and i felt I need your confirmation before having this test there, that's why committed the test as a separate file. 
On the other note, what I'm able to see upon running this test is what I expected, based on the manual search done by me and the values for the search have been taken from tests.py file.

**Comment by mathuin** [comment]
The test should go into `pgd_search/tests.py` as a new class, perhaps something like `SaveImageAfterSearch`.

When I ran the test by hand, I received an exception about not being able to load a profile.  I think that's related to the setup code.

How Firefox-specific is your test?  Can it be run with selenium?

**Comment by Sentient07** [comment]
Sure, i will move it there. The test worked perfect for me. But, yes, there was something I was supposed to add as a disclaimer. I initially had similar problem because selenium(or one of the dependencies) didn't support the current version of firefox. So I had to upgrade one of the packages, and after I did that it worked fine for me. I thought it was some system specific issue and didn't take a notice of which package I updated. I hope maybe updating some packages would solve the issue,
The related packages and their versions
nose==1.3.4
nose-cov==1.6
selenium==2.45.0

**Comment by Sentient07** [comment]
So I guess I need to rebase now to make the PR look clean ? Or should I add anything more ?

**Comment by mathuin** [comment]
Rebasing to develop and adding those new requirements to the requirements.txt file will help.  Once that's done it'll be easier for me to test your code!

**Pull request closed without merging**
