### PR TITLE
GSoC 2014 Code PR

### PR DESCRIPTION
**Pull request by mathuin**
This pull request contains all the code created by last year's Google Summer of Code participant for the PGD as merged into our current develop branch.

All tests pass.  A short selection file containing 100 proteins worked correctly.  I am now doing a full-scale import of 26504 proteins.  After that finishes, I will perform some standard searches.  If those searches work, I will +1 the PR.

I am eager to receive constructive input from others.  Thanks in advance!

### CODE REVIEW

**Comment by mathuin** [comment]
As of this morning, the database contains 26489 proteins.  15 proteins were skipped.  One (4D1J) was skipped due to a deadlock -- this protein was imported with no errors using the instructions found in the documentation for "CRC check failed" and other errors.  The remaining 14 were skipped because their files were not found on the local system.  Of the proteins with files not found locally, none were found on the FTP site.  Nine proteins were superseded by other models.  The remainder have no PDB files on the site but do have PDBx and PDBML files which implies that they are too large for the PDB format.

Details on the superseded proteins:
- 4K2W was superceded by 4YET
- 2GL6 was superceded by 4Z9M
- 3RD1 was superseded by 4Y0V
- 4R1X was superseded by 4RVN
- 3U42 was superseded by 4REO
- 4UYC was superseded by 5AFP
- 4W83 was superseded by 4YFJ
- 2GOI was superseded by 4YF2
- 4EXU was superseded by 4YNO

This behavior is perfectly consistent with that observed by production.

**Comment by mathuin** [comment]
Static files are no longer served by default when using runserver.

There are two alternatives:  one is to modify the Dockerfile to use nginx, another is to use the `--insecure` flag for `runserver`.  I will be going with the latter, as the cookbook should take care of the former.

**Comment by mathuin** [comment]
Okay.  +1 from me!

**Comment by pop** [comment]
Looks like PGD to me :thumbsup:

**Pull request merged**
