### PR TITLE
Deprecation fixes

### PR DESCRIPTION
**Pull request by mathuin**
Once we installed the develop branch on the staging site, we discovered some additional issues:  a problem with settings.py and settings.py.dist and a dangling print statement were top of the list.

I also fixed the SECRET_KEY being in the settings.py file which required updating the Dockerfile, and I also updated the documentation including the README.md which was imported as part of the GSoC 2014 code.

### CODE REVIEW

**Comment by mathuin** [comment]
@ElijahCaine Half of this is what we've already done, the other half is important yet harmless IMHO.  If you can look it over and +1 it, I'll put it into develop.  The staging site is running this branch and has no trouble.

**Comment by pop** [comment]
@mathuin So you've decided to get rid of settings.py.dist in favor of just settings.py?

Besides that it looks +1 worthy.

**Comment by mathuin** [comment]
I think replacing settings.py.dist with settings.py makes sense here.

Using the decouple module allows us to create a viable default configuration (sans SECRET_KEY) and makes it easy to change that configuration in a number of ways -- settings.ini for production, ENV in Docker for development.  When the student tests email this summer, he will be able to do so by tweaking the environment to use a different email backend or a fake server or something, and it'll be easier to transition between development and production by using something like this.

Do you see a downside to using settings.py instead of a dist file?

**Comment by pop** [comment]
I totally agree; settings.py.dist and settings.ini both achieve the same goal so we don't need both. :thumbsup: from me.

**Comment by mathuin** [comment]
Excellent!

**Pull request merged**
