### PR TITLE
Improved sidechain statistics test.

### PR DESCRIPTION
**Pull request by mathuin**
The previous test checked for the presence of a value, so I improved
it to check for the actual correct values for a number of parameters.
It can be extended to cover other elements in other sidechains as
well, should that be necessary.

### CODE REVIEW

**Comment by mathuin** [comment]
@Kennric let me know what you think!

**Comment by iankronquist** [comment]
Looks good to me. +1

**Comment by mathuin** [comment]
@iankronquist can you check this again?  The changes I made took care of that intermittent failure, and also check results.  Thanks!

**Comment by mathuin** [comment]
@iankronquist I rebased this after the release, it should be fine, check again?

**Comment by iankronquist** [comment]
Looks good to me. +1

**Comment by mathuin** [comment]
Thanks!

**Pull request merged**
