### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by iankronquist**
This is very preliminary. The Dockerfile works, but I need to add docs.
The biggest change is that I added a dependency, python-decouple, which was recommended by @mythmon as a way to use and environment variable based config. Mozilla uses it in a couple projects, and it looks like a clean solution.
I also changed the settings.py.dist to use decouple.
Sample docker commands might look like:

``` shell
$ docker build -t osl_test/pgd .
$ docker run --name pgd_mysql -e MYSQL_ROOT_PASSWORD=pgd_mysql -e MYSQL_USER=root -e MYSQL_PASSWORD=pgd_db -e MYSQL_DATABASE=pgd_db -d mysql
$ docker run --name pgd --link pgd_mysql:mysql osl_test/pgd
```

### CODE REVIEW

**Comment by mathuin** [comment]
Two thoughts:
- This pull request includes #5 so I will test #5 first
- The config changes will need to be integrated with the cookbook -- please make another pull request in the cookbook repo and reference this one so they are in sync.
  Other than that I am very hopeful! :-)

**Comment by iankronquist** [comment]
Whoops, I didn't realize that this included #5. Let me fix that.
The old configuration should work as is, but I will fix the cookbook.

**Comment by iankronquist** [comment]
Hmmm cherry-picking the right commits to a new branch and force pushing doesn't work. I'll look at this on Monday.

**Comment by iankronquist** [comment]
So apparently I can't fix this. Let's try again.

**Pull request closed without merging**
