### PR TITLE
Redundant svg/issue/17799

### PR DESCRIPTION
**Pull request by iankronquist**
This needs more testing, but it should be set.

### CODE REVIEW

**Comment by iankronquist** [comment]
@mathuin r+?

**Comment by mathuin** [comment]
Wow, this goes way back. :-)  The changes to `develop` were sufficiently significant that this would need to be rebased first -- can you do that first?

**Comment by mathuin** [comment]
@iankronquist is this still something you'd like to do, or should I do it?

**Comment by iankronquist** [comment]
@Mathuin I want to do it sometime this coming week.

**Comment by mathuin** [comment]
@iankronquist ?

**Comment by iankronquist** [comment]
This is on my radar. I'm trying to get a bunch of zombie PRs merged. If you just want to get it done go ahead and take it.

**Pull request closed without merging**
